### ISSUE TITLE
Bug In translation 

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/synaptic#12]
The authentication window (com.ubuntu.pkexec.synaptic) shows the title in English "Authentication is required to run synaptic packge manager", it is not being translated into Brazilian Portuguese. This package is translated in Ubuntu.
Report: https://bugs.launchpad.net/linuxmint/+bug/1684300
![2oq2iz9](https://cloud.githubusercontent.com/assets/8754997/26533674/d369cf06-43f2-11e7-9dcb-6c160396e175.png)

**Comment by GabrielMGitHub** [comment]
Report: https://bugs.launchpad.net/linuxmint/+bug/1684300

**Comment by GabrielMGitHub** [comment]
@clefebvre OPEN!

**Comment by clefebvre** [comment]
Weird.. the policy file contains the translation though..

    <message xml:lang="pt_BR">Autenticação é exigida para executar o Gerenciador de Pacotes Synaptic</message>

**Comment by clefebvre** [comment]
Can you run the following and see what happens?

`pkexec synaptic`

Also check the content of /usr/share/polkit-1/actions/com.ubuntu.pkexec.synaptic.policy on your filesystem.

**Comment by GabrielMGitHub** [comment]
I can not do the test now because my HD burned. But you can do the test yourself, and only select the Portuguese language of Brazil and download the language pack and take the tests.

**Comment by GabrielMGitHub** [comment]
The title of the window is not being translated, even by downloading the language pack.
"Authentication is required to run synaptic packge manager"
Below the title is translated.

**Comment by clefebvre** [comment]
OK, this is very weird...

`sudo nano /usr/share/polkit-1/actions/com.ubuntu.pkexec.synaptic.policy`

If I change:

<message xml:lang="pt_BR">Autenticação é exigida para executar o Gerenciador de Pacotes Synaptic</message>

to:

<message xml:lang="pt">Autenticação é exigida para executar o Gerenciador de Pacotes Synaptic</message>

It works.

Looking at Ubuntu though, they have the same policy file as us... they use pt_BR, not pt... 

Policykit should properly detect pt_BR and work with it, so I'm not happy with that fix.

**Comment by clefebvre** [comment]
In which version of Ubuntu does this work?

**Comment by GabrielMGitHub** [comment]
This is not a fix until we have downloaded the language package pt_BR and not pt_PT.

**Comment by GabrielMGitHub** [comment]
Versions 16.04, 16.10, 17.04, and earlier.

**Comment by GabrielMGitHub** [comment]
Is this a translation of an XML or an MO file?

**Comment by clefebvre** [comment]
It's this file:
/usr/share/polkit-1/actions/com.ubuntu.pkexec.synaptic.policy

**Comment by clefebvre** [comment]
It's upstream from us. 

![16 04 2](https://user-images.githubusercontent.com/1138515/27005205-5d90641a-4e11-11e7-9b25-924e05faa038.png)

This is the same bug reproduced in Ubuntu 16.04.2. Language is pt_BR, pkexec fails to use the pt_BR translation provided in  /usr/share/polkit-1/actions/com.ubuntu.pkexec.synaptic.policy.
